# backend/render.yaml

services:
  - type: web
    name: store-ratings-api
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start:prod"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: store-ratings-db # <-- Make sure this matches the name of your Render database
          property: externalUrl
      - key: JWT_SECRET
        generateValue: true # Render will generate a random secret for you